version: "3"

services:
  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    container_name: 'local-food-drug-service'

    ports:
      - '8167:8167'
    networks:
      - proxy_net

networks:
  proxy_net:
   name: custom_network